name: TWRP Recovery Builder 2024

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'TWRP Minimal-Manifest Branch'
        required: true
        default: 'twrp-14' # Установлено значение по умолчанию
        type: choice
        options:
        - twrp-14
        - twrp-12.1
        - twrp-11
        - twrp-9.0
      DEVICE_TREE:
        description: 'Custom Recovery Tree' 
        required: true
        default: 'https://github.com/Baratynsky/recovery_device_xiaomi_moon'
      DEVICE_TREE_BRANCH:
        description: 'Custom Recovery Tree Branch' 
        required: true
        default: 'twrp-14-a15' # Изменено на актуальную ветку
      DEVICE_PATH:
        description: 'Specify your Device Path' 
        required: true
        default: 'device/xiaomi/moon'
      DEVICE_NAME:
        description: 'Specify your Device Codename' 
        required: true
        default: 'moon'
      BUILD_TARGET:
        description: 'Specify your Build Target' 
        required: true
        default: 'vendorboot'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot

jobs:
  build:
    name: Build TWRP by ${{ github.actor }}
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v4 # Обновлено до v4

    - name: Display Inputs
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Tree: ${{ github.event.inputs.DEVICE_TREE }}"
        echo "Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}image"
        echo "::endgroup::"

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
      
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24
        
    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib lib32ncurses5-dev x11proto-core-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libtinfo5 libgflags-dev
        sudo add-apt-repository universe
        sudo apt -y install libncurses5

    - name: Install OpenJDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install Git-Repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Check Manifest Branch
      id: manifest
      uses: haya14busa/action-cond@v1
      with:
        cond: ${{ github.event.inputs.MANIFEST_BRANCH == 'twrp-11' || github.event.inputs.MANIFEST_BRANCH == 'twrp-12.1'  || github.event.inputs.MANIFEST_BRANCH == 'twrp-14' }}
        if_true: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
        if_false: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git

    - name: Initialize Repo
      run: |
        mkdir workspace
        cd workspace
        git config --global user.name "Samuel Kendall"
        git config --global user.email "kinguser981@gmail.com"
        repo init --depth=1 -u ${{ steps.manifest.outputs.value }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
  
    - name: Repo Sync
      run: |
        cd workspace
        repo sync -j$(nproc --all) --force-sync

    - name: Clone Device Tree
      run: |
        cd workspace
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
        cd ${{ github.event.inputs.DEVICE_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

    # ШАГ СБОРКИ БЫЛ ЗНАЧИТЕЛЬНО ИЗМЕНЕНЕН
    - name: Build TWRP
      run: |
        # ИСПРАВЛЕНИЕ: Определяем имя makefile и настоящее имя выходного файла
        # Имя файла, который создает система сборки, может отличаться от цели make
        DEVICE_MAKEFILE="twrp_${{ github.event.inputs.DEVICE_NAME }}"
        BUILD_TARGET_COMMAND="${{ github.event.inputs.BUILD_TARGET }}image"
        
        # ИСПРАВЛЕНИЕ: Определяем правильное имя выходного файла
        if [ "${{ github.event.inputs.BUILD_TARGET }}" = "vendorboot" ]; then
          OUTPUT_IMAGE_NAME="vendor_boot.img"
        else
          OUTPUT_IMAGE_NAME="${{ github.event.inputs.BUILD_TARGET }}.img"
        fi
        echo "OUTPUT_IMAGE_NAME=${OUTPUT_IMAGE_NAME}" >> $GITHUB_ENV
        
        # Запускаем сборку
        cd workspace
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        # ИСПРАВЛЕНИЕ: lunch теперь использует напрямую созданную переменную
        lunch
        make clean
        make ${BUILD_TARGET_COMMAND} -j$(nproc --all)
        echo "Done building your image."

    - name: Set Build Date
      run: echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

    # ШАГ ПРОВЕРКИ ВЫХОДНОГО ФАЙЛА ИЗМЕНЕН
    - name: Check if Recovery Image Exists and Set Variables
      id: check_image
      run: |
        cd workspace
        IMG_PATH="out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ env.OUTPUT_IMAGE_NAME }}"
        if [ -f "$IMG_PATH" ]; then
          echo "Image file '${{ env.OUTPUT_IMAGE_NAME }}' found!"
          echo "IMAGE_FOUND=true" >> $GITHUB_OUTPUT
          echo "MD5_IMG=$(md5sum $IMG_PATH | cut -d ' ' -f 1)" >> $GITHUB_ENV
        else
          echo "No Recovery file found at $IMG_PATH!"
          echo "IMAGE_FOUND=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        
    # ШАГ ВЫГРУЗКИ ИЗМЕНЕН
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: steps.check_image.outputs.IMAGE_FOUND == 'true'
      with:
        files: |
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ env.OUTPUT_IMAGE_NAME }}
        name: Unofficial TWRP for ${{ github.event.inputs.DEVICE_NAME }} | ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Target: ${{ env.OUTPUT_IMAGE_NAME }}
          Device: [Device Tree/Branch](${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ github.event.inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
          MD5 Checksum: `${{ env.MD5_IMG }}`
